builders:
  post_get_builder:
    import: "package:new_flutter_bloc/builder.dart"
    builder_factories: ["postGetBuilder"]
    build_extensions: {".dart": [".post_get"]}
    auto_apply: root_package
    build_to: source
    runs_before: ["source_gen|combining_builder"]
